version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in install phase
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - my_release=$(awk '/deb .*\/debian/{print $3; exit}' /etc/apt/sources.list)
      - (cd debian && ./bootstrap.sh -c $my_release)
      - sed -i debian/control -e '/^#/d' && sed -i debian/control -e '/^$/N;/^\n$/D'
      - mk-build-deps -i  -t "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
      - make -f debian/rules .stamp-configure
      - dpkg-buildpackage -b -rfakeroot -us -uc
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ../*.deb