version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in install phase
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - my_release=$(awk '/deb .*\/debian/{print $3; exit}' /etc/apt/sources.list)
      - (cd debian && ./bootstrap.sh -c $my_release)
      - sed -i debian/control -e '/^#/d' && sed -i debian/control -e '/^$/N;/^\n$/D'
      - mk-build-deps -i  -t "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
      - make -f debian/rules .stamp-configure
      - dpkg-buildpackage -b -rfakeroot -us -uc
      - cd $CODEBUILD_SRC_DIR_sounds
      - ./debian.sh freeswitch-sounds-en-us-callie
      - s3cmd --verbose --delete-removed --follow-symlinks  sync s3://s3-apt-repo/ /opt/repo/
      - reprepro -b /opt/repo removematched production '*freeswitch*' 
      - reprepro -b /opt/repo includedeb production ../*.deb
      - s3cmd --verbose --delete-removed --follow-symlinks  sync  /opt/repo/ s3://s3-apt-repo/
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ../*.deb